import { AUTH_TYPE, AWSAppSyncClient } from "aws-appsync";
import { AppSyncIdentityCognito, AppSyncResolverEvent } from "aws-lambda";
import { gql } from "graphql-tag";
import { createChat, updateChat } from "./mutations";
import { parseStreamLine } from "./stream-parser";
import { CreateChatMutation, CreateChatMutationVariables } from "./types";

interface Arguments {
    sessionId: string;
    human: string;
    memoryEnabled?: boolean;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    sessionAttributes?: Record<string, any>;
}

// The `errorState` field is added in schema.graphql; the Amplify-generated types
// are regenerated by codegen after deploy. Until then, extend the input locally.
type UpdateChatInput = {
    id: string;
    human?: string;
    assistant?: string;
    trace?: string;
    traceMetadata?: string;
    errorState?: string;
};

const FIRST_BYTE_TIMEOUT_MS = 60_000;

/**
 * Build the AgentCore Runtime invocation URL for HTTPS (bearer-token) invocation.
 * The runtime uses inbound Cognito auth, so we cannot use the SDK; we POST the
 * caller's JWT as a bearer token (Req 11.1, 11.7).
 */
function buildInvocationUrl(runtimeArn: string, endpoint: string, region: string): string {
    const encodedArn = encodeURIComponent(runtimeArn);
    return `https://bedrock-agentcore.${region}.amazonaws.com/runtimes/${encodedArn}/invocations?qualifier=${encodeURIComponent(
        endpoint
    )}`;
}

export const handler = async (event: AppSyncResolverEvent<Arguments>) => {
    const { sessionId, human, memoryEnabled, sessionAttributes } = event.arguments;
    const identity = event.identity as AppSyncIdentityCognito | undefined;
    const bearerToken = event.request.headers.authorization;

    const graphqlClient = new AWSAppSyncClient({
        url: process.env.GRAPH_API_URL!,
        region: process.env.AWS_REGION!,
        auth: {
            type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
            jwtToken: bearerToken!,
        },
        disableOffline: true,
    });

    const mutateUpdate = (input: UpdateChatInput) =>
        graphqlClient.mutate({
            mutation: gql`
                ${updateChat}
            `,
            variables: { input },
        });

    // --- Guards ------------------------------------------------------------
    // Empty/whitespace sessionId: reject without invoking the runtime (Req 5.5).
    if (!sessionId?.trim()) {
        return "error: sessionId is required";
    }
    // Missing identity: reject (Req 11.8).
    if (!identity?.username || !bearerToken) {
        return "error: unauthenticated";
    }

    // --- Create the Chat record --------------------------------------------
    const { id } = (
        (await graphqlClient.mutate({
            mutation: gql`
                ${createChat}
            `,
            variables: {
                input: {
                    sessionId,
                    expiration: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 7, // 7 days
                },
            } as CreateChatMutationVariables,
        })) as { data: CreateChatMutation }
    ).data.createChat!;

    // --- Invoke the runtime over HTTPS with the caller's bearer token ------
    const url = buildInvocationUrl(
        process.env.AGENTCORE_RUNTIME_ARN!,
        process.env.AGENTCORE_RUNTIME_ENDPOINT ?? "default",
        process.env.AWS_REGION!
    );

    const controller = new AbortController();
    const firstByteTimer = setTimeout(() => controller.abort(), FIRST_BYTE_TIMEOUT_MS);

    let assistant = "";
    const traceEvents: unknown[] = [];

    // AgentCore's data-plane endpoint treats a non-"Bearer" Authorization header as
    // an AWS SigV4 signature and rejects it with HTTP 403. The JWT authorizer is
    // only engaged when the caller's token is sent as a bearer token, so we must
    // prefix "Bearer " (AppSync forwards the raw JWT without it).
    const authorizationHeader = bearerToken.startsWith("Bearer ")
        ? bearerToken
        : `Bearer ${bearerToken}`;

    try {
        const response = await fetch(url, {
            method: "POST",
            headers: {
                Authorization: authorizationHeader,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                prompt: human,
                sessionId,
                actorId: identity.username,
                memoryEnabled: !!memoryEnabled,
                ...sessionAttributes,
            }),
            signal: controller.signal,
        });

        if (!response.ok || !response.body) {
            throw new Error(`runtime invocation failed: HTTP ${response.status}`);
        }

        // Stream items framed as SSE (`data: {json}`) or raw NDJSON:
        //   {"type":"chunk","text":...} | {"type":"trace","event":...}
        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        let firstByteSeen = false;

        // eslint-disable-next-line no-constant-condition
        while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            if (!firstByteSeen) {
                firstByteSeen = true;
                clearTimeout(firstByteTimer); // first byte arrived within the window (Req 5.6)
            }
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split("\n");
            buffer = lines.pop() ?? "";
            for (const line of lines) {
                const item = parseStreamLine(line);
                if (!item) continue;
                if (item.type === "chunk" && typeof item.text === "string") {
                    assistant += item.text; // incremental completion (Req 5.2)
                } else if (item.type === "trace" && item.event !== undefined) {
                    traceEvents.push(item.event); // ordered trace stream (Req 5.3)
                }
                await mutateUpdate({
                    id,
                    human,
                    assistant,
                    trace: item.type === "trace" ? JSON.stringify(item.event) : undefined,
                    traceMetadata: JSON.stringify(traceEvents),
                });
            }
        }

        // Flush any trailing buffered line (streams may omit a final newline).
        const tail = parseStreamLine(buffer);
        if (tail) {
            if (tail.type === "chunk" && typeof tail.text === "string") {
                assistant += tail.text;
            } else if (tail.type === "trace" && tail.event !== undefined) {
                traceEvents.push(tail.event);
            }
            await mutateUpdate({
                id,
                human,
                assistant,
                trace: tail.type === "trace" ? JSON.stringify(tail.event) : undefined,
                traceMetadata: JSON.stringify(traceEvents),
            });
        }

        return assistant;
    } catch (err) {
        // Runtime failure or first-byte timeout: preserve written completion,
        // record an error state, return an error indication (Req 5.6).
        clearTimeout(firstByteTimer);
        const message = err instanceof Error ? err.message : "unknown error";
        await mutateUpdate({
            id,
            human,
            assistant,
            errorState: `invocation did not complete: ${message}`,
        });
        return `error: ${message}`;
    } finally {
        clearTimeout(firstByteTimer);
    }
};
